server:
  port:
    8088
spring:
  application:
    name:
      My Demo SSMRT
  thymeleaf:
    cache: false  # 官方建议在开发时将缓存关闭
  redis:
    database: 0             # Redis数据库索引（默认为0）
    host: localhost         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）
    #timeout: 1000           # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        # max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 0         # 连接池中的最小空闲连接
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
